export const scTrack = {
  kind: 'track',
  sharing: 'public',
  id: 123,
  urn: 'soundcloud:tracks:123',
  title: 'New title',
  permalink_url: 'https://soundcloud.com/artist/new-slug?utm_source=api',
  artwork_url: 'https://i1.sndcdn.com/art.jpg',
  duration: 125500,
  created_at: '2026-09-20T12:00:00Z',
  genre: 'rap',
  metadata_artist: 'Artist',
  stream_url: 'https://api.soundcloud.com/tracks/123/stream',
  download_url: 'audio',
  description: 'Do not store',
  playback_count: 999999,
  user: {
    id: 45,
    urn: 'soundcloud:users:45',
    username: 'Uploader',
    permalink_url: 'https://soundcloud.com/artist',
    avatar_url: 'https://i1.sndcdn.com/avatar.jpg',
  },
};
