/**
 * Original test copy written in the voice of underground rap communities.
 * Placeholders: {artist}, {producer} (only used when a credit exists), {title}.
 */
export type Persona = {
  username: string;
  bio: string;
  scenes: string[];
  lower: boolean;
};

export const personas: Persona[] = [
  {
    username: 'bellsandbags',
    bio: 'plugg til the wheels fall off 🔔 saving rare stuff before it blows',
    scenes: ['plugg', 'pluggnb'],
    lower: true,
  },
  {
    username: 'midnightvamp',
    bio: 'rage + cloud rap. if it doesnt make me want to jump off something i skip',
    scenes: ['rage', 'cloud rap'],
    lower: true,
  },
  {
    username: 'jerkszn',
    bio: 'jerk drums are a lifestyle. nyc',
    scenes: ['jerk', 'rage'],
    lower: true,
  },
  {
    username: 'eeriemode',
    bio: 'dark plugg and whatever this weird stuff is. headphones only',
    scenes: ['dark plugg', 'experimental'],
    lower: true,
  },
  {
    username: 'pinkglitch',
    bio: 'Hyperpop kid who grew up and found the underground. Glitch everything.',
    scenes: ['hyperpop', 'experimental'],
    lower: false,
  },
  {
    username: 'flipthesample',
    bio: 'Sample drill + UK. I will tell you where the sample is from whether you asked or not',
    scenes: ['sample drill', 'UK underground'],
    lower: false,
  },
  {
    username: 'eastsidetape',
    bio: 'detroit flows, memphis tapes. fast rap appreciation society',
    scenes: ['Detroit', 'Memphis'],
    lower: true,
  },
  {
    username: 'cowbelltapes',
    bio: 'tape hiss, cowbells, darkness. memphis forever',
    scenes: ['Memphis', 'dark plugg'],
    lower: true,
  },
  {
    username: 'cloudyafternoons',
    bio: 'cloud rap for rainy days, pluggnb for the drive home',
    scenes: ['cloud rap', 'pluggnb'],
    lower: true,
  },
  {
    username: 'londonlate',
    bio: 'UK underground mostly. night bus soundtrack curator.',
    scenes: ['UK underground', 'sample drill'],
    lower: false,
  },
  {
    username: '808diary',
    bio: 'i rate everything. dont take it personal',
    scenes: ['plugg', 'rage'],
    lower: true,
  },
  {
    username: 'sauceonmyheart',
    bio: 'pluggnb heartbreak specialist 💔 melodies over everything',
    scenes: ['pluggnb', 'plugg'],
    lower: true,
  },
  {
    username: 'nopitchcorrection',
    bio: 'experimental / hyperpop. the weirder the mix the better',
    scenes: ['experimental', 'hyperpop'],
    lower: true,
  },
  {
    username: 'earlybirdlistener',
    bio: 'If it has under 10 saves I probably found it first. Rage, jerk, plugg.',
    scenes: ['rage', 'jerk', 'plugg'],
    lower: false,
  },
  {
    username: 'basementcdq',
    bio: 'dark plugg digger. still looking for the cdq of everything',
    scenes: ['dark plugg', 'plugg'],
    lower: true,
  },
  {
    username: 'slowdownrewind',
    bio: 'cloud rap + memphis. slowed is not a crime',
    scenes: ['cloud rap', 'Memphis'],
    lower: true,
  },
  {
    username: 'molly_static',
    bio: 'hyperpop x rage crossover enjoyer. loud music only',
    scenes: ['hyperpop', 'rage'],
    lower: true,
  },
  {
    username: 'snippetseason',
    bio: 'living off snippets until they drop. rage and pluggnb',
    scenes: ['rage', 'pluggnb'],
    lower: true,
  },
  {
    username: 'rarefind_rae',
    bio: 'Plugg and cloud rap. Here for the producers honestly.',
    scenes: ['plugg', 'cloud rap'],
    lower: false,
  },
  {
    username: 'tapehiss',
    bio: 'memphis and detroit. lofi mixes > clean mixes',
    scenes: ['Memphis', 'Detroit'],
    lower: true,
  },
  {
    username: 'kickdrumkev',
    bio: 'jerk and detroit. if it bounces im in',
    scenes: ['jerk', 'Detroit'],
    lower: true,
  },
  {
    username: 'northlinegoth',
    bio: 'Dark plugg + UK. Gloomy music for gloomy weather.',
    scenes: ['dark plugg', 'UK underground'],
    lower: false,
  },
  {
    username: 'lowsaves',
    bio: 'experimental + plugg. sorting by least saves since day one',
    scenes: ['experimental', 'plugg'],
    lower: true,
  },
  {
    username: 'nightbus_audio',
    bio: 'UK underground and cloud rap. late night listening only',
    scenes: ['UK underground', 'cloud rap'],
    lower: true,
  },
  {
    username: 'hoodiesummer',
    bio: 'pluggnb + jerk. hoodie on in july type music',
    scenes: ['pluggnb', 'jerk'],
    lower: true,
  },
];

export const highReviews = [
  'i keep coming back to this one, it just feels right every time',
  '{artist} doesnt get enough credit for how good their ear for beats is',
  'the hook is stuck in my head and i am not complaining',
  'this is the song that got me into {artist}',
  'the bass on this rattles my whole room',
  'so much atmosphere in two and a half minutes',
  '{producer} really made the beat sound like it is underwater, in the best way',
  'bro snapped',
  'added to every playlist i have',
  'the opening ten seconds are enough to know',
  'this deserves to be way bigger than it is',
  '{artist} sounds so comfortable on this, like they werent even trying and it still goes crazy',
  'nothing else sounds like this rn',
  'the drums are so crisp, whoever mixed this deserves a raise',
  'sent this to the group chat and everyone went silent then said run it back',
  'late night walk music. perfect',
  'the melody at the end lives rent free in my head',
  'this hits harder every time',
  '{title} is a top 3 {artist} song and i will die on that hill',
  '{producer} production is unmatched, the layers on this are crazy',
  'the energy never drops once',
  'genuinely made my week',
  'the flow switch in the second verse is so smooth',
  'i keep showing this to people and they all end up saving it',
  'underrated is an understatement',
  'these melodies are on another level',
  'i can tell this one is going to age really well',
  'loud, messy, perfect',
  'the vibe is immaculate',
  'how do you make something sound this sad and this hard at the same time',
  'i played this for 20 minutes straight and didnt notice',
  'pure replay value',
  'every second of the beat is doing something interesting',
  'if you only listen to one {artist} song make it this one',

  'this go stupid hard. replayed it like 6 times on the way to class',
  '{producer} has been cooking all year and this might be the best one',
  'the way the beat opens up after the first verse… i had to pull over',
  '{artist} really said let me make the hardest song in the underground real quick',
  'music is so back. this is the one',
  'the synths on this are actually ethereal. headphones mandatory',
  'lowkey a perfect song. not a wasted second',
  'the bounce on this is crazy, cannot play it in the car without speeding',
  'i need a longer version asap, the outro ends way too soon',
  '{title} has been on repeat since tuesday. it is genuinely a problem',
  'people sleeping on {artist} is criminal fr',
  'beat switch at the end had me screaming',
  'every time i think im over this one i hear the hook again and im back',
  'slept on this for months and now its my most played. dont be like me',
  'the adlibs alone deserve 5 stars',
  'hearing this at 2am hits different, trust',
  'this is the one i send to people who say the underground is mid',
  'the mix is a little muddy and i dont even care, the energy carries the whole thing',
  '{producer} tag at the start and you already know its over (in a good way)',
  'cold. cold. cold.',
  'genuinely do not understand how this only has a handful of saves',
  'first listen i thought it was mid, third listen its top 10 of the year. certified grower',
  'vocals are mixed kinda low but it works, feels like a dream',
  'this is what i want every song to sound like',
  '{artist} on a {producer} beat should be illegal, they need a whole tape together',
  'perfect length, perfect hook, no notes',
];

export const midReviews = [
  'nice beat, forgettable verses',
  '{artist} sounds a little bored on this one',
  'its fine but i expected more after the intro',
  'good for the gym, not much else',
  'the hook is great, everything else is just there',
  'solid 3.5, would not skip if it came on',
  'i like it but it feels unfinished',
  'nice energy but the mix is kind of flat',
  'decent song, great artwork honestly',
  'one listen was enough but it was a good listen',
  'mood dependent. some days it hits, some days i skip',
  'not their best, not their worst',

  'solid but the hook goes on a bit too long',
  'beat is crazy, the verses are just ok',
  'good vibes, not something id run back a lot though',
  '{producer} carried this one honestly',
  'decent. the first minute is way better than the rest',
  'kinda sounds like a few other songs i heard this month but its still fun',
  'the snippet was harder than the release ngl',
  'mid on first listen, might grow on me',
  'love the melody, wish the drums hit harder',
  'too short to really judge but what is there is nice',
  'background music that occasionally goes crazy',
  '{artist} has better ones but this still slaps in the right mood',
  'production 9/10, vocals 6/10',
  'one of those songs i like more when it comes on shuffle than when i choose it',
];

export const lowReviews = [
  'the beat deserved a better song',
  'sounds rushed',
  'too repetitive for me, same four bars the whole time',
  'i get why people like it but it is not clicking',
  'this one did not age well for me',

  'not for me. the autotune is fighting the beat the whole time',
  'the beat is cool but the vocals feel like a rough take',
  'i wanted to like this so bad',
  'skip. {artist} has way better stuff, start somewhere else',
  'feels like a loosie for a reason',
  'mix is rough, the 808 is eating everything',
  'one good bar and that is it',
];

export const sceneLines: Record<string, string[]> = {
  plugg: [
    'plugg is not dead, it just went back underground where it belongs',
    'those bells 🔔 pure plugg',
    'nostalgic plugg sound, takes me straight back to 2019 soundcloud',
  ],
  pluggnb: [
    'pluggnb for the late night drives',
    'the melodies are so sweet, pluggnb heaven',
    'pure pluggnb heartbreak music, im fine 🙂',
  ],
  rage: [
    'rage synths turned all the way up, mosh pit certified',
    'this would destroy a live crowd',
    'the distorted 808s on this are insane',
  ],
  jerk: [
    'jerk drums so bouncy i cant sit still',
    'this is the jerk sound ive been looking for',
    'the drum pattern is doing something illegal',
  ],
  'dark plugg': [
    'eerie in the best way',
    'dark plugg at its creepiest, love it',
    'sounds like a haunted video game level and i mean that as a compliment',
  ],
  hyperpop: [
    'so chaotic and i love every second',
    'the pitched vocals are unreal',
    'glitchy perfection',
  ],
  'sample drill': [
    'that sample flip is crazy',
    'did not expect that sample, perfect drill switch up',
    'the way the sample gets chopped on the second verse 😮‍💨',
  ],
  Detroit: [
    'detroit flow is unmatched',
    'the energy on this is pure detroit',
    'fast flows, no breaths, detroit really does it different',
  ],
  Memphis: [
    'the memphis influence is so obvious and so good',
    'cowbells and darkness, memphis vibes all day',
    'the tape hiss mix is exactly right',
  ],
  experimental: [
    'no idea what genre this is and i love that',
    'weird in the best way',
    'like nothing ive heard this year',
  ],
  'cloud rap': [
    'floating on this one',
    'hazy and perfect for rainy days',
    'cloud rap that sounds like 2013 tumblr in the best way',
  ],
  'UK underground': [
    'the uk scene is so slept on',
    'flows are so different from the us stuff, refreshing',
    'uk producers are just built different',
  ],
};

export const comments = [
  'the bridge on this 😮‍💨',
  'this is so underrated',
  'i swear i found this before it had any saves',
  'car test passed',
  'what is the sample on this',
  'need this slowed',
  'need this sped up honestly',
  'this one feels like summer 2021',
  'replaying this all week',
  '{producer} cooked fr',
  'they need to perform this live',
  'the ending caught me off guard',

  'who produced this?? need more like it',
  'anyone know if theres a longer version',
  'this needs to be on streaming',
  'found this through earlyworld and its my most played now',
  '3am vibes',
  'the outro 😭',
  'W',
  'this deserves way more saves',
  '{artist} never misses',
  'the way this starts',
  'the tag at the beginning 🔥',
  'been looking for this one for weeks',
  'played this for my friends and they all asked who it was',
  'how is this not everywhere yet',
  'the second half >>>',
  'this is the one for real',
  'need {artist} and {producer} on a full tape',
  'early. mark my words',
  'ok this is going in every playlist',
  'chills on the hook every time',
];

export const releaseReviews = [
  'every song sounds like it belongs, really cohesive',
  'the closer is one of the best songs they have',
  'great tape, slightly too many interludes',
  'i didnt expect much and it ended up on repeat',
  'the features are better than the solo songs',
  'really strong production, the vocals are hit or miss',

  'front to back no skips',
  'track 3 is the standout for me',
  'a little long but the highs are really high',
  'the sequencing is perfect, the transitions are so smooth',
  'my favorite tape of the year so far',
  'half of this is amazing, the other half is filler',
  'production is consistent the whole way through',
  '{artist} found their sound on this one',
  'needs a couple more listens but the opener is crazy',
  'short and to the point. respect',
];

export const ownerConversations = {
  match: [
    'yo we matched on some rare ones, how did you even find those',
    { share: true as const },
    'this one is next if you havent heard it',
  ],
  request: ['hey saw your saves, you got great taste. what scenes are you mostly into?'],
  group: {
    name: 'diggers gc',
    lines: [
      ['a', 'made a gc for people who actually dig'],
      ['b', 'W'],
      ['c', { share: true as const }],
      ['c', 'first track of the day'],
      ['a', 'this is so good, adding it to everything'],
    ] as [string, string | { share: true }][],
  },
};
